### ISSUE TITLE
launcher.ts can consume chrome-launcher directly

### ISSUE THREAD

**Issue by samccone** [sonarwhal/sonar#311]
I was checking out 
`src/lib/collectors/cdp/cdp-launcher.ts`

and noticed that you have your own version of chrome launcher. I think you can easily use `chrome-launcher` which we pulled out of lighthouse to satisfy this exact usecase!

https://github.com/GoogleChrome/lighthouse/tree/master/chrome-launcher#launching-chrome

---

Let me know if you have any questions, and or encounter any issues. I am more than happy to help y'all delete a bunch of code and push the responsibility over to us :D

**Comment by molant** [comment]
Yup, I saw that the other day :)
IIRC, I'm doing some extra magic with the launcher because during the tests we launch multiple instances of chrome and I was having problems with it back in the day, but worth looking into it :)

@sarvaje can you look into this as part of #297 ?

**Comment by samccone** [comment]
> because during the tests we launch multiple instances of chrome

So launching multiple versions of chrome without hitting port collisions is supported out of the box :)

passing no port to chrome:
https://github.com/GoogleChrome/lighthouse/blob/master/chrome-launcher/chrome-launcher.ts#L86
will call into our open port finder
https://github.com/GoogleChrome/lighthouse/blob/master/chrome-launcher/random-port.ts#L14

the remote debugging port will then be returned as part  the launched chrome interface
https://github.com/GoogleChrome/lighthouse/blob/master/chrome-launcher/chrome-launcher.ts#L36


An example of a more complex chrome-pool:
https://github.com/gwuhaolin/chrome-pool


---

Let me know if you run into any problems!

**Comment by molant** [comment]
OK, after reviewing the code and making some memory I think I remember what I did and why. We are using avajs for testing so tests run in parallel. While this is awesome, it will force us to open many, many instances of Chrome and (in Travis especially) that isn't great. That's why I'm storing the [pid on a file](https://github.com/sonarwhal/sonar/blob/master/src/lib/collectors/cdp/cdp-launcher.ts#L36), checking if it exists, etc. so we can reuse it from independent processes.

We also add the option to run headless [if on CI](https://github.com/sonarwhal/sonar/blob/master/src/lib/collectors/cdp/cdp-launcher.ts#L266) (but should actually be a collector option).

Again, I think this is why we did it. If there is a better way to achieve the same thing or this could be interesting for `chrome-launcher` let us know and we'll do a PR (i think the headless option as a parameter at least would be nice)!

**Comment by samccone** [comment]
> We also add the option to run headless [if on CI](https://github.com/sonarwhal/sonar/blob/master/src/lib/collectors/cdp/cdp-launcher.ts#L266) (but should actually be a collector option).

headless chrome is easy with chrome launcher :) .. We did not hardcode a headless mode as it is nothing more than two flags:

```
const chrome = await chromeLauncher.launch({
  startingUrl: 'https://google.com',
  chromeFlags: ['--headless', '--disable-gpu']
});
 
console.log(`Chrome debugging port running on ${chrome.port}`);
```


> I think I remember what I did and why. We are using avajs for testing so tests run in parallel. While this is awesome, it will force us to open many, many instances of Chrome and (in Travis especially) that isn't great

When you launch chrome via launcher we expose the pid for you, so you could use a semaphore (funny enough i wrote a lib for this a long time ago https://github.com/samccone/promise-semaphore) + a fixed number of launched chrome instances to deal with this problem.

---

At a high level, chrome launcher is a primitive, for launching chrome, composing it with other tools is pushed out into user land.

I think based on your requirements we are providing enough primitives for what you want to do, but let me know if anything else is missing.

**Comment by sarvaje** [comment]
>@sarvaje can you look into this as part of #297 ?
sure!
