### ISSUE TITLE
Remove system-specific carriage returns

### ISSUE THREAD

**Issue by rachelnabors** [sonarwhal/sonar#564]
Looks like there's a Window's specific carriage return goofing things up on my Mac: 

```
Rachels-MacBook-Pro-2:reloaded rachel$ sonar
env: node\r: No such file or directory
```

## Environment
Mac, running NVM. Am unable to create `.sonarrc`.

* __`Node.js` version: v8.6.0
* __`npm` version: 5.3.0

**Comment by molant** [comment]
Been talking with @rachelnabors, it looks like this happens with any command in the CLI.
Trying to pinpoint where the error comes from as @alrra is using a Mac and doesn't repro this with the latest version. Maybe an issue with `nvm`?

**Comment by alrra** [comment]
> Maybe an issue with nvm?

The problem is not with `nvm` (I'm using it, and everything is working fine).

> `#!/usr/bin/env node` was causing sonar to throw 

`#!/usr/bin/env node` should be there so that the system knows what to use (i.e. `node`, not `sh`, or something else) [when the file is executed directly](https://github.com/sonarwhal/sonar/blob/6ae98f33cf0b40d5edbbdbd7fbdafddd96dc331a/package.json#L151) (and not as `node some_file.js`)

Note: I've reverted #564, as otherwise, this will happen (for all users) when trying to execute `sonar`:

```bash
/Users/alrra/.nvm/versions/node/v8.1.3/bin/sonar: line 1: use strict: command not found
/Users/alrra/.nvm/versions/node/v8.1.3/bin/sonar: line 2: syntax error near unexpected token `exports,'
/Users/alrra/.nvm/versions/node/v8.1.3/bin/sonar: line 2: `Object.defineProperty(exports, "__esModule", { value: true });'
```

> `#!/usr/bin/env node` was causing sonar to throw  `env: node\r: No such file or directory` from the command line on my Mac.

The problem is that, for some reason, on @rachelnabors' system there is a `\n` after `node`, so the system tries to execute the file using `node\r` instead of `node`, which of course doesn't exist, hence `No such file or directory`.

> Looks like there's a Window's specific carriage return goofing things up on my Mac:

I don't see any carriage return in the code, nor the generated code from `dist/` (or in the published package).

**Comment by alrra** [comment]
I can confirm issue using `npm` `v5.3.0`.

**Comment by alrra** [comment]
@molant I think the problem is that when you did the release, when the build process was executed it automatically inserted the `\r`. :(

**Comment by alrra** [comment]
I published a [new release](https://github.com/sonarwhal/sonar/releases/tag/0.10.2) that should fix this issue.

---

@rachelnabors Can you reinstall `sonar`, and confirm this issue has been fixed? Thanks!
