### ISSUE TITLE
Create an APi

### ISSUE THREAD

**Issue by grantkemp** [sonarwhal/sonar#597]
1. Propose a new feature/change:
Create a generic api that can create tests and provide a callback to notify on result. ( similar to webpagetest) 
Allow presentation formats of JSON, CSV, Html

eg: https://sites.google.com/a/webpagetest.org/docs/advanced-features/webpagetest-restful-apis

**Comment by molant** [comment]
Hi @grantkemp,

If I've understood correctly you want an API for the online service, correct? If that's the case, there is no plan for that. The reason is that behind the scenes we use the same code than this project, we just have a bunch of containers running it and some code to orchestrate it. You can take a look in the [online-service project](https://github.com/sonarwhal/online-service). 

I'd recommend you to use the command line directly, take a look at the [getting started guide](https://sonarwhal.com/docs/user-guide). There's already support for different result outputs by [changing the formatter](https://sonarwhal.com/docs/user-guide/formatters/index.html). If there are more you'd like to see, please open an issue for each one! The CLI will also allow you to tweak the configuration, what rules you want to run, what should be a warning or an error, etc.

Thanks!

**Comment by grantkemp** [comment]
Thanks @molant - If there is a plan to do this there is a tool we have used elsewhere that will allow scaling and also orchestrating it in multiple territories - I am happy to help with this - but wanted to make sure it was something that was going to be potentially considered.  

Since its not on the list - will leave it for now - but thank you for sharing an awesome tool - I would like to include it in a talk I am doing at a conference in a few weeks.

**Comment by alrra** [comment]
> I would like to include it in a talk I am doing at a conference in a few weeks.

@grantkemp Let us know if we can help with any information.
