### ISSUE TITLE
Protocol-relative URLs on HTTPS only sites should not generate a warning

### ISSUE THREAD

**Issue by hannob** [sonarwhal/sonar#605]
I noticed that on my site the scan complains about protocol-relative URLs. I don't think it's valid to see this as a security issue.

However my site is available over HTTPS only. It uses HSTS and forwards all HTTP traffic to HTTPS. Therefore a protocol-relative URL is equivalent to an HTTPS URL.

I see protocol-relative URLs on HTTPS sites as a micro-optimization. It saves a few bytes. Arguably not a whole lot, but I don't see a reason not to do it.

**Comment by alrra** [comment]
> I noticed that on my site the scan complains about protocol-relative URLs.
>
> However my site is available over HTTPS only. It uses HSTS and forwards all HTTP traffic to HTTPS. Therefore a protocol-relative URL is equivalent to an HTTPS URL.

@hannob We are planning to make the scanner ([as with the CLI](https://sonarwhal.com/docs/user-guide/#ruleconfiguration)) allow users to submit their custom configurations so that if the user considers  that a rule is not useful in their case, and they want to ignore the defaults, they are able to.

> However my site is available over HTTPS only. It uses HSTS and forwards all HTTP traffic to HTTPS. Therefore a protocol-relative URL is equivalent to an HTTPS URL.

Did you also submit your site to the [HTTP Strict Transport Security (HSTS) preload list](https://hstspreload.org/)? If not, there still is a chance that the first request is made by the user over HTTP, is intercepted, the HSTS header is removed, and so on.

See: https://sonarwhal.com/docs/user-guide/rules/strict-transport-security.html#whyisthisimportant.

Also, another reason why the rule suggests not using protocol-relative URLs is because (and we've seen this in the wild), sometimes, even if everything is ok, servers get misconfigured and out of the sudden sites are served over HTTP until their owner(s) see the problem.

Here is the [full documentation on why this rule exists and is enabled by default](https://sonarwhal.com/docs/user-guide/rules/no-protocol-relative-urls.html#whyisthisimportant).

---

Note: Rules are made to check for what we as a community agree are best practices for the time being. If for some reason in a user's case they don't want to follow the recommendation but are still doing everything right, that's perfectly fine (reason why we allow in the CLI to disable rules). But, the majority of people don't do everything right, and also things can change over time (or mistakes are made), so that's why we prefer to be more strict by default.

Hope this answers your question on why we push for not using  protocol-relative URLs.
